### ISSUE TITLE
ssh爆破报错

### ISSUE THREAD

**Issue by TryA9ain** [zyylhn/zscan#5]
环境为win2008 r2

z.exe ssh --hostfile linux.txt -U root -P root

z.exe ssh -H ip -U root -P root

![image](https://user-images.githubusercontent.com/51145610/145349804-72457dec-e104-431b-8c68-e84e4d8470aa.png)

**Comment by zyylhn** [comment]
ssh爆破的话需要加上-b，不加-b默认是登录需要指定用户名密码，可以排除一下用其他的ssh客户端去连接目标看看能不能连上我觉得可能是服务器那面的问题

**Comment by TryA9ain** [comment]
> ssh爆破的话需要加上-b，不加-b默认是登录需要指定用户名密码，可以排除一下用其他的ssh客户端去连接目标看看能不能连上我觉得可能是服务器那面的问题

了解，-b就可以了
