### ISSUE TITLE
关于zscan代理功能使用出现的严重问题

### ISSUE THREAD

**Issue by sairson** [zyylhn/zscan#6]
我发现了zscan一个致命的问题，我想知道这个问题是否有解决方法，当使用proxy代理后，在进行端口扫描，会发现，所设置的所有端口均会为返回成功，我设置了1-100端口，并尝试ps模块的端口扫描
![image](https://user-images.githubusercontent.com/74412075/147536558-dd61b01a-4a3e-41e8-952f-7942e0279541.png)
我研究了zscan的源码，发现是socks5代理连接的问题。这使得你的zscan扫描在走代理后将完全不准确

其次程序运行中会出现net.Func的error问题
![image](https://user-images.githubusercontent.com/74412075/147536406-eb3360ad-66c5-4fb2-aec1-b9e89c2294ee.png)
这是一个非常严重的错误，他将会完全印象程序的使用，望修改

**Comment by zyylhn** [comment]
能否提供一下使用的命令和测试环境，会尽快修改

**Comment by sairson** [comment]
测试环境，win10 1909版本，参数是 zscan.exe all -H ip --porxy 127.0.0.1:1080，当程序走代理后，无法准确的识别端口,其次是在执行后，过一段事件会抛出net.Func的panic错误

**Comment by sairson** [comment]
哦，对了，我在学习你github代码的时候，发现了一个小问题
![image](https://user-images.githubusercontent.com/74412075/148151445-b7565e1a-9152-4158-bc3f-daa9d6e553c5.png)
mongdb的认证，你打成了postgre_auth，我想，这可能是意外的问题，不知道是否会影响代码的执行😊😀

**Comment by sairson** [comment]
哈哈哈，对了，我解决你的mongodb不能走代理的方法了，只需要
![image](https://user-images.githubusercontent.com/74412075/148179398-18febc4c-ba38-43a4-b90f-7f816998c172.png)
设置如上方式即可走代理扫描

**Comment by sairson** [comment]
有空师傅加个好友？

**Comment by zyylhn** [comment]
可以，微信号发我邮箱

**Comment by zyylhn** [comment]
对代码有什么建议欢迎提出来，会采纳用于后期重构

**Comment by sairson** [comment]
可以加一个winrm的扫描和命令执行，ladongo的代码就可以参考
